# Generated by Django 5.1.7 on 2025-03-25 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_numarasi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('pdf', models.FileField(upload_to='makaleler/')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
