# Generated by Django 5.1.7 on 2025-03-25 20:45

import makale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='takip_numarasi',
            field=models.CharField(default=makale.models.benzersiz_takip_no_uret, editable=False, max_length=10, unique=True),
        ),
    ]
