# Generated by Django 5.1.7 on 2025-03-25 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0002_alter_makale_takip_numarasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
    ]
