# Generated by Django 5.1.7 on 2025-03-26 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0003_mesaj'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonimlestirmeSecimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.BooleanField(default=False)),
                ('e_posta', models.BooleanField(default=False)),
                ('kurum', models.BooleanField(default=False)),
                ('makale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
    ]
