# Generated by Django 5.1.7 on 2025-03-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0004_anonimlestirmesecimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='guncellendi',
            field=models.BooleanField(default=False),
        ),
    ]
