# Generated by Django 5.1.7 on 2025-03-26 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0005_makale_guncellendi'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='anonim_pdf',
            field=models.FileField(blank=True, null=True, upload_to='anonim/'),
        ),
        migrations.AddField(
            model_name='makale',
            name='kurum',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='HakemDegerlendirmesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('degerlendirme_pdf', models.FileField(blank=True, null=True, upload_to='degerlendirme/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
        migrations.CreateModel(
            name='LogKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
    ]
