# Generated by Django 5.1.7 on 2025-03-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0006_makale_ad_soyad_makale_anonim_pdf_makale_kurum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='kullanici_gonderdi',
            field=models.BooleanField(default=False),
        ),
    ]
