# Generated by Django 5.1.7 on 2025-03-27 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0007_mesaj_kullanici_gonderdi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HakemeYollamaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('hakem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.hakem')),
                ('makale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
    ]
