# Generated by Django 5.1.7 on 2025-03-27 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0008_hakem_hakemeyollamakaydi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakemeyollamakaydi',
            name='degerlendirme_pdf',
            field=models.FileField(blank=True, null=True, upload_to='degerlendirmeler/'),
        ),
        migrations.AlterField(
            model_name='hakemeyollamakaydi',
            name='makale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale'),
        ),
    ]
