# Generated by Django 5.1.7 on 2025-03-27 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0009_hakemeyollamakaydi_degerlendirme_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HakemDegerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
    ]
