# Generated by Django 5.1.7 on 2025-03-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0010_hakemdegerlendirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakemdegerlendirme',
            name='hakem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='makale.hakem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hakemdegerlendirme',
            name='tamamlandi',
            field=models.BooleanField(default=False),
        ),
    ]
