# Generated by Django 5.1.7 on 2025-04-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0011_hakemdegerlendirme_hakem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hakemdegerlendirme',
            options={'verbose_name': 'Hakem Değerlendirmesi', 'verbose_name_plural': 'Hakem Değerlendirmeleri'},
        ),
        migrations.AlterModelOptions(
            name='hakemeyollamakaydi',
            options={'verbose_name': 'Hakem Atama Kaydı', 'verbose_name_plural': 'Hakem Atama Kayıtları'},
        ),
        migrations.AlterField(
            model_name='hakemdegerlendirme',
            name='makale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makale.makale'),
        ),
        migrations.AlterField(
            model_name='hakemeyollamakaydi',
            name='makale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makale.makale'),
        ),
    ]
