# Generated by Django 5.1.7 on 2025-04-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0012_alter_hakemdegerlendirme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='degerlendirme_pdf',
            field=models.FileField(blank=True, null=True, upload_to='degerlendirmeler/'),
        ),
    ]
